// Do not edit this file.

// Package metadata provides framework info registered to registry.
package metadata

// constant for sdk version, name, registration component
const (
	SdkVersion                    = "0.1"
	SdkName                       = "Go-Chassis"
	SdkRegistrationComponent      = "SDK"
	PlatformRegistrationComponent = "PLATFORM"
)
