// Code generated by go-chassis/scripts/version_set.sh. DO NOT EDIT.

// Package metadata provides framework info registered to registry.
package metadata

// constant for sdk version, name, registration component
const (
	SdkVersion                    = "v2.0.0-alpha.5"
	SdkName                       = "Go-Chassis"
	SdkRegistrationComponent      = "SDK"
	PlatformRegistrationComponent = "PLATFORM"
)
