// Code generated by go-chassis/scripts/version_set.sh. DO NOT EDIT.

// Package metadata provides framework info registered to registry.
package metadata

// constant for sdk version, name, registration component
const (
	SdkVersion                    = "1.8.3"
	SdkName                       = "Go-Chassis"
	SdkRegistrationComponent      = "SDK"
	PlatformRegistrationComponent = "PLATFORM"
)
