// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package employ is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	EmployStruct
	EmployRequest
	EmployResponse
*/
package employ

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmployStruct struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Phone string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
}

func (m *EmployStruct) Reset()                    { *m = EmployStruct{} }
func (m *EmployStruct) String() string            { return proto.CompactTextString(m) }
func (*EmployStruct) ProtoMessage()               {}
func (*EmployStruct) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EmployStruct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmployStruct) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type EmployRequest struct {
	Name       string          `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Employ     *EmployStruct   `protobuf:"bytes,2,opt,name=employ" json:"employ,omitempty"`
	EmployList []*EmployStruct `protobuf:"bytes,3,rep,name=employList" json:"employList,omitempty"`
}

func (m *EmployRequest) Reset()                    { *m = EmployRequest{} }
func (m *EmployRequest) String() string            { return proto.CompactTextString(m) }
func (*EmployRequest) ProtoMessage()               {}
func (*EmployRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EmployRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EmployRequest) GetEmploy() *EmployStruct {
	if m != nil {
		return m.Employ
	}
	return nil
}

func (m *EmployRequest) GetEmployList() []*EmployStruct {
	if m != nil {
		return m.EmployList
	}
	return nil
}

type EmployResponse struct {
	Employ     *EmployStruct   `protobuf:"bytes,1,opt,name=employ" json:"employ,omitempty"`
	EmployList []*EmployStruct `protobuf:"bytes,2,rep,name=employList" json:"employList,omitempty"`
}

func (m *EmployResponse) Reset()                    { *m = EmployResponse{} }
func (m *EmployResponse) String() string            { return proto.CompactTextString(m) }
func (*EmployResponse) ProtoMessage()               {}
func (*EmployResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EmployResponse) GetEmploy() *EmployStruct {
	if m != nil {
		return m.Employ
	}
	return nil
}

func (m *EmployResponse) GetEmployList() []*EmployStruct {
	if m != nil {
		return m.EmployList
	}
	return nil
}

func init() {
	proto.RegisterType((*EmployStruct)(nil), "employ.EmployStruct")
	proto.RegisterType((*EmployRequest)(nil), "employ.EmployRequest")
	proto.RegisterType((*EmployResponse)(nil), "employ.EmployResponse")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xcd, 0x2d, 0xc8, 0xc9, 0xaf, 0x54, 0xb2,
	0xe0, 0xe2, 0x71, 0x05, 0xb3, 0x82, 0x4b, 0x8a, 0x4a, 0x93, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2,
	0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e, 0xd6,
	0x82, 0x8c, 0xfc, 0xbc, 0x54, 0x09, 0x26, 0xb0, 0x20, 0x84, 0xa3, 0xd4, 0xce, 0xc8, 0xc5, 0x0b,
	0xd1, 0x1a, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x8c, 0x5d, 0xaf, 0x0e, 0x17, 0xd4, 0x26, 0xb0, 0x66,
	0x6e, 0x23, 0x11, 0x3d, 0x08, 0x57, 0x0f, 0xd9, 0xd6, 0x20, 0xa8, 0x1a, 0x21, 0x13, 0x2e, 0x2e,
	0x08, 0xcb, 0x27, 0xb3, 0xb8, 0x44, 0x82, 0x59, 0x81, 0x19, 0xa7, 0x0e, 0x24, 0x75, 0x4a, 0x25,
	0x5c, 0x7c, 0x30, 0x87, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0x23, 0xdb, 0xca, 0x48, 0xb2, 0xad, 0x4c,
	0xc4, 0xd9, 0x9a, 0xc4, 0x06, 0x0e, 0x48, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x59,
	0x31, 0xd4, 0x56, 0x01, 0x00, 0x00,
}
