// Code generated by protoc-gen-go. DO NOT EDIT.
// source: healthz.proto

/*
Package client is a generated protocol buffer package.

It is generated from these files:
	healthz.proto

It has these top-level messages:
	Request
	Reply
*/
package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The response message containing the greetings
type Reply struct {
	AppId       string `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=serviceName" json:"serviceName,omitempty"`
	Version     string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Reply) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *Reply) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Reply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "client.Request")
	proto.RegisterType((*Reply)(nil), "client.Reply")
}

func init() { proto.RegisterFile("healthz.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x48, 0x4d, 0xcc,
	0x29, 0xc9, 0xa8, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce, 0xc9, 0x4c, 0xcd,
	0x2b, 0x51, 0xe2, 0xe4, 0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0x8a, 0xe4, 0x62,
	0x0d, 0x4a, 0x2d, 0xc8, 0xa9, 0x14, 0x12, 0xe1, 0x62, 0x4d, 0x2c, 0x28, 0xf0, 0x4c, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x14, 0xb8, 0xb8, 0x8b, 0x53, 0x8b, 0xca, 0x32,
	0x93, 0x53, 0xfd, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x72, 0xc8, 0x42, 0x42, 0x12, 0x5c, 0xec,
	0x65, 0xa9, 0x45, 0xc5, 0x99, 0xf9, 0x79, 0x12, 0xcc, 0x60, 0x59, 0x18, 0xd7, 0x49, 0x83, 0x4b,
	0x3c, 0x33, 0x5f, 0x2f, 0xbd, 0xa8, 0x20, 0x59, 0x2f, 0x39, 0x23, 0xb1, 0xb8, 0x38, 0xb3, 0x58,
	0x0f, 0xea, 0x1c, 0x27, 0x6e, 0x0f, 0x30, 0xc3, 0x39, 0x23, 0x35, 0x39, 0x3b, 0x80, 0x31, 0x89,
	0x0d, 0xec, 0x3c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xa7, 0x10, 0x51, 0xaf, 0x00,
	0x00, 0x00,
}
