name: Merge check
on: [push, pull_request]
jobs:
  build:
    name: Merge check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build
      run: go build -v .
    - name: UT
      run: |
        bash scripts/ci/start_latest_sc.sh
        go get github.com/stretchr/testify
        bash scripts/ci/unit_test.sh
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go
      - name: Fmt
        run: |
          bash scripts/ci/formatChecker.sh
      - name: Misspell
        run: |
          go get -u github.com/client9/misspell/cmd/misspell
          bash scripts/ci/formatChecker.sh
      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          bash scripts/ci/goLintChecker.sh
      - name: Cyclo
        run: |
          go get github.com/fzipp/gocyclo
          bash scripts/ci/goCycloChecker.sh